# DO NOT EDIT THIS FILE

.PHONY: test check

build:
	dune build

code:
	-dune build
	code .
	! dune build --watch

utop:
	OCAMLRUNPARAM=b dune utop lib

test:
	OCAMLRUNPARAM=b dune exec test/main.exe

zip:
	rm -f order_book.zip
	zip -r order_book.zip . -x@exclude.lst

doc:
	dune build @doc

clean:
	dune clean
	rm -f order_book.zip

opendoc: doc
	@bash opendoc.sh